spring:
  application:
    name: commerce-backend
  jpa:
    show-sql: true
    database-platform: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;mode=mysql
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      platform: h2

server:
  port: 8080